---
# tasks file for roles/flask-webapp
- name: delete the old web server container
  community.docker.docker_container:
    name: flask-webapp
    state: absent

- name: Create new container from the new image
  community.docker.docker_container:
    name: flask-webapp
    state: present
    mounts:
      - source: /home/ubuntu/jenkins_home
        target: /var/jenkins_home
        type: bind
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind  
    ports:
      - 80:8080
    restart_policy: always
    detach: true
    image: "anas1243/simple-webapp-flask:{{ lookup('ansible.builtin.env','BUILD_ID') }}"